# Site settings
title: Memory house
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Weifan
baseurl: "go" # the subpath of your site, e.g. /blog/
url: "yrwfhome.me"# the base hostname & protocol for your site
